<a href="https://colab.research.google.com/github/Tkag0001/AI_and_Machine_Learning_for_Coders/blob/main/Chapter5_Introduction_to_Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Natural Language Processing
![Introduce image](https://bobcares.com/wp-content/uploads/2024/11/Natural-Language-Processing.png)

Đến với chương 5 này tụi mình sẽ cùng nhau tìm hiểu về **NLP** nha. Đây cũng là chủ đề chính trong một vài chương tiếp theo của chúng ta luôn nha.

> **NLP là gì?**

**NLP** là viết tắt của cụm từ **Natural language processing**, dịch thô có nghĩa là **xử lý ngôn ngữ tự nhiên**, là một nhánh trong lĩnh vực trí tuệ nhân tạo.

Mọi người có thể hiểu đơn giản là **NLP** liên quan đến các công nghệ mà ở đó các thiết bị hay máy tính có thể hiểu được ngôn ngữ người dùng, thực hiện được các tác vụ như phân loại nội dung, phân tích ngữ cảnh, cũng như tạo ra các văn bản, thành phần ở mức ngôn ngữ con người.


## Ứng dụng của NLP:
Cái này thì quá đơn giản rồi ha, gần nhất với mọi người sử dụng hàng ngày là **Chatbot**.

Các ứng dụng khác có thể kể đến như là xác định các đối tượng trong văn bản, phân loại bình luận tích cực hay tiêu cực,...

Tuy nhiên trong mục tiêu, phạm vi của cuốn sách lần này, chúng ta chỉ đơn giản là tìm hiểu **NLP** theo hướng tiếp cận cơ bản, hiểu được cách mô hình hóa ngôn ngữ, nhờ đó có thể huấn luyện mô hình để thực hiện các tác vụ như là hiểu và phân loại nội dung văn bản.

Bắt đầu chương này, tụi mình sẽ đến với phần tìm hiếu cách để chuyển từ dữ liệu văn bản sang dạng số, cũng như sử dụng chính những số đó cho mô hình neural nha.

# Encoding Language into Numbes.(Mã hóa ngôn ngữ thành chữ số)

Đầu tiên tụi mình sẽ đến với phần mã hóa, chuyển đổi ngôn ngữ thành dạng chữ số nha.

> **Tại sao lại cần chuyển đổi từ văn bản thành dạng số?**

Mình nghĩ để giải thích dễ dàng nhất thì là thuận tiện cho việc đưa vào các công thức tính toán.

![Encoding image](https://files.readme.io/bf9ae1b-Iwanttobreakfree.png)

> **Vậy câu hỏi đặt ra là chúng ta sẽ mã hóa chúng như thế nào ?**

Thực ra là có rất nhiều cách để mã hóa.
Đơn giản nhất đi ha là tụi mình sẽ tiến hành phân tích mã hóa theo kí tự.

## Mã hóa theo kí tự (Character tokenizer)

Mã hóa theo kí tự tức mỗi kí tự sẽ tương ứng với một số, qua đó một từ hay một câu sẽ là một vector hay chuỗi số. Điển hình mà mọi người có thể thấy rõ nhất là bộ mã **ASCII** ha.

VD. Chiếu theo bộ mã ASCII ta sẽ có:
- **"Dead is like the wind, always by my side"** -> [68, 101, 97, 100, 32, 105, 115, 32, 108, 105, 107, 101, 32, 116, 104, 101, 32, 119, 105, 110, 100, 44, 32, 97, 108, 119, 97, 121, 115, 32, 98, 121, 32, 109, 121, 32, 115, 105, 100, 101]



```python
D: 68
e: 101
a: 97
d: 100
 : 32
i: 105
s: 115
 : 32
l: 108
i: 105
k: 107
e: 101
 : 32
t: 116
h: 104
e: 101
 : 32
w: 119
i: 105
n: 110
d: 100
,: 44
 : 32
a: 97
l: 108
w: 119
a: 97
y: 121
s: 115
 : 32
b: 98
y: 121
 : 32
m: 109
y: 121
 : 32
s: 115
i: 105
d: 100
e: 101

```



Tuy nhiên mọi người sẽ gặp phải một vấn đề nha. Trong một số trường hợp, chúng sẽ ảnh hưởng đến mô hình nên đây cũng là điểm hạn chế của mã hóa theo kí tự.

Sẽ có một số từ sẽ có số lượng kí tự lẫn các kí tự y chang nhau chỉ là thay đổi về số lượng từ thôi. Mặc dù là thứ tự cũng có khác đấy nhưng mà nó vẫn gây khó khăn trong việc hiểu được nội dung của mô hình.

Những trường hợp từ như vậy gọi là **antigram**.
Mình ví dụ một số từ như là:
- Santa - Satan
- restful - fluster
- forty five - over fifty

Có một joke nghe hơi dark dựa trên **antigram** là:
> **"Evangelist is the Evil's Agent."** 💀



Thay vào đó tụi mình sẽ có một cách thay thế tốt hơn là mã hóa theo từ.

## Mã hóa theo từ (Word tokenizer)
Hiểu đơn giản là với mỗi từ tụi mình sẽ có một số để đại diện cho từ đó.

```python
# "Caption Teemo on duty" -> [1, 2, 3, 4]
vocabulary = {
  "Caption": 1,
  "Teemo": 2
  "on": 3,
  "duty": 4
}
```

Tuy nhiên chúng có sẽ có các hạn chế khác, tụi mình sẽ bàn sau ha. Còn bây giờ đi vào ví dụ code cụ thể trước nha.

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

org_texts = [
    "Today is a sunny day",
    "Today is a rainy day"
]


# Định nghĩa số lượng từ trong công cụ mã hóa (tokenizer)
tokenizer = Tokenizer(num_words = 100)
# Tiến hành đẩy các từ vào để tạo thư viện từ trong công cụ mã hóa.
tokenizer.fit_on_texts(org_texts)
# Lấy từ điển mã hóa ra
word_index = tokenizer.word_index
print(word_index)

{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}


Như đây là kết quả của đoạn code ở trên nha, chúng ta sẽ lấy được từ điển mã hóa từ như sau

```python
{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}
```
Như mọi người thấy, mỗi từ sẽ được lưu lại và được đại diện bởi một con số mã hóa.

Sau khi đẩy các chuỗi vào để tạo từ điển, tụi mình sẽ tiến mã hóa các chuỗi hay câu với hàm **texts_to_sequences** nha. Mọi người chỉ cần chuyển list các câu vào.


In [2]:
sequences = tokenizer.texts_to_sequences(org_texts)
print(sequences)

[[1, 2, 3, 5, 4], [1, 2, 3, 6, 4]]


Kết quả của chuỗi hoàn toàn tương đồng với số mã hóa ở trên.

> **Vậy điểm hạn chế của phương pháp mã hóa theo từ là gì?**

Như mọi người thấy, chúng hoạt động dựa trên các từ có sẵn trong từ điển. Vậy, khi gặp những **từ mới** không có trong thư viện từ vựng, máy tính sẽ không thể phát hiện được dẫn đến chúng **bỏ qua** nó, lúc này khi ta cho mô hình học chúng sẽ không được học đầy đủ và có thể bị nhầm lẫn ngữ cảnh.

Ví dụ như đoạn code dưới đây.

In [3]:
# Tập kiểm tra
test_data = [
    "Today is a snowy day",
    "Will it be rainy tomorrow?"
]

# Tiến hành mã hóa
test_seq = tokenizer.texts_to_sequences(test_data)

# Kiểm tra kết quả mã hóa.
print(test_seq)

[[1, 2, 3, 4], [6]]


Như mọi người thấy kết quả mã hóa của 2 câu như sau:

```python
 "Today is a snowy day" - [1, 2, 3, 4]
 "Will it be rainy tomorrow?" - [6]
 ```
Độ dài của chuỗi sau mã hóa đã bị giảm đi rất nhiều, chúng chỉ mã hóa được những từ đã biết, nhưng từ chưa biết thì bỏ qua.

Chúng ta có tên gọi cụ thể của trường hợp này là  **Out of vocabulary**, tức nằm ngoài vùng từ vựng.

## Using Out of vocabulary tokens (Sử dụng các token cho từ vựng mới)

> Vậy chúng ta có thể giải quyết vấn đề **Out of vocabulary** này như thế nào?

Có nhiều cách mã hóa cải tiến để khắc phục hoặc hạn chế ảnh hưởng của tình trạng này. Ở đây mình chỉ giới thiệu cách đơn giản nhất thôi ha.
Mọi người sẽ sử dụng một **token hay số** để đại diện cho các trường hợp **từ vựng không biết trước**.

Ở đây mình sẽ sử dụng token là **< OOV >** nha. Mọi người có thể đặt tên token là cái khác cũng được. Trong một số mô hình hay đoạn code mọi người có thể bắt gặp nó dưới dạng **< UNK >** có nghĩa là **unknown - không biết**.

In [4]:
# Tiến hành định nghĩa lại bộ mã hóa, thêm vào token đại diện cho trường hợp từ không biết
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
# Tiến hành đẩy các từ vào để tạo thư viện từ trong công cụ mã hóa.
tokenizer.fit_on_texts(org_texts)

In [5]:
# In từ điển bên trong bộ mã hóa ra
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'today': 2, 'is': 3, 'a': 4, 'day': 5, 'sunny': 6, 'rainy': 7}


**Ở đây mọi người sẽ thấy từ vựng không biết sẽ được đánh số mã hóa là 1**

In [6]:
# Tiến hành mã hóa lại các câu gặp phải trường hợp từ vựng không biết trước đó
test_seq = tokenizer.texts_to_sequences(test_data)
print(test_seq)

[[2, 3, 4, 1, 5], [1, 1, 1, 7, 1]]


Mọi người có thể thấy kết quả sau khi thêm vào token cho trường hợp từ vựng không biết:


```python
"Today is a snowy day" - [2, 3, 4, 1, 5]
 "Will it be rainy tomorrow?" - [1, 1, 1, 7, 1]
```



Tuy nó không phải là cách tối ưu nhất nhưng chúng ta đã có thể đi đúng hướng giải quyết rồi. Tiếp đên tụi mình cùng tìm hiểu về phần đệm chuỗi nha.

## Understanding padding

Hiểu đơn giản thì là **đệm thêm các token vào chuỗi**. Như mọi người đã biết dữ liệu khi đưa vào mô hình học tập thì **phải có kích thước giống nhau, tương ứng với kích thước đầu vào của mô hình**.

Ở các chương trước, khi chúng ta làm việc với dữ liệu dạng ảnh, chúng ta đã tiến hành điều chỉnh lại kích thước ảnh trước khi đưa vào mô hình thì bây giờ khi xử lý dữ liệu dạng chuỗi cũng tương tự như vậy á.

Với dữ liệu dạng chuỗi chúng ta sẽ thêm vào các token đại diện cho những phần tử đệm thêm vào với mục đích làm cho độ dài các chuỗi đều tương đương nhau. Mọi người sẽ thường bắt gặp token này với dạng **< PAD >>** trong các mô hình xử lý.

Nói đủ nhiều rồi, bây giờ chúng ta sẽ đi vào code xử lý cụ thể ha.

In [7]:
# Các câu văn cần mã hóa để đưa vào mô hình
sentences = [
  "Today is a sunny day",
  "Today is a rainy day",
  "Is it sunny today?",
  "I really enjoyed walking in the snow today"
]

# Định nghĩa bộ mã hóa
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

# Tiến hành mã hóa các câu văn
sequences = tokenizer.texts_to_sequences(sentences)

In [8]:
# In ra kết quả mã hóa
for seq in sequences:
  print(seq)

[2, 3, 4, 5, 6]
[2, 3, 4, 7, 6]
[3, 8, 5, 2]
[9, 10, 11, 12, 13, 14, 15, 2]


Như mọi  người thấy đấy, chúng có kích thước không giống nhau nha.


```python
[2, 3, 4, 5, 6]
[2, 3, 4, 7, 6]
[3, 8, 5, 2]
[9, 10, 11, 12, 13, 14, 15, 2]
```
Bây giờ tụi mình sẽ tiến hành đệm vào để giúp độ dài các chuỗi có cùng kích thước với chuỗi có độ dài nhất.


In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tiến hành đệm các chuỗi
padded = pad_sequences(sequences)

# In ra kết quả đệm
print("Kết quả các câu đã đệm:")
for seq in padded:
  print(seq)

Kết quả các câu đã đệm:
[0 0 0 2 3 4 5 6]
[0 0 0 2 3 4 7 6]
[0 0 0 0 3 8 5 2]
[ 9 10 11 12 13 14 15  2]


Như mọi người thấy, bây giờ các chuỗi đều đã có kích thước là 8 ha. Tuy nhiên các số 0 đại diện token **< PAD >** lại được đệm ở đầu. Đây cũng là lý do mà thường các bộ mã hóa có từ điển bắt đầu từ 1 ha, số 0 sẽ dành cho phần **padding**.

Việc thêm bộ đệm ở phần đầu này tụi mình sẽ gọi là **prepadding**.

Nếu mọi người muốn thêm bộ đệm ở phía sau, mọi người có thể dùng thêm một tham số nhỏ là **padding = 'post'** cho phương thức trên.

In [10]:
padded = pad_sequences(sequences, padding='post')
print("Kết quả các câu đã đệm:")
for seq in padded:
  print(seq)

Kết quả các câu đã đệm:
[2 3 4 5 6 0 0 0]
[2 3 4 7 6 0 0 0]
[3 8 5 2 0 0 0 0]
[ 9 10 11 12 13 14 15  2]


Đấy, các số 0 đã được đệm vào phần đuôi rồi này, qua đó giúp đảm bảo kích thước các batch trước khi đưa vào huấn luyện mô hình.

Thông qua việc thêm các bộ đệm vào, thì tụi mình đã có thể đảm bảo đươc độ dài các thành phần trong batch. Tuy nhiên bạn cũng sẽ đối mặt với một trường hợp đặc biệt.
> **Điều gì sẽ xảy ra nếu bạn gặp phải một câu dài đến mức điên rồ ?**

Đứng vậy, bạn sẽ phải thêm một mớ bộ đệm vào, một câu chỉ có 3 4 từ nhưng lại thêm cả chục token **< PAD >** vào chỉ vì để cùng độ dài với một câu dài đến mức điên rồ. Và đôi khi nó có thể lấn át dữ liệu hữu ích hay tốn quá nhiều thời gian và tài nguyên để xử lý. **Đó là một sự đánh đổi**.

Để khắc phục tình trạng đó, ta có thể định nghĩa thêm một tham số gọi là độ dài tối đa **maxlen** để giới hạn lại độ dài chuỗi. Tuy nhiên chúng cũng sẽ có những **đánh đổi nhất định**.

In [11]:
padded = pad_sequences(sequences, padding='post', maxlen=6)
print("Kết quả các câu đã đệm:")
for seq in padded:
  print(seq)

Kết quả các câu đã đệm:
[2 3 4 5 6 0]
[2 3 4 7 6 0]
[3 8 5 2 0 0]
[11 12 13 14 15  2]


Như mọi người thấy đấy, các chuỗi đã được giới hạn lại tối đa độ dài, ba chuỗi đầu chỉ được thêm từ 0 đến 1 token **< PAD >** hay số 0 để đảm bảo đạt độ dài tối đa.

Trong khi đó chuỗi cuối cùng lại được cắt ngắn chỉ còn 6 kí tự cuối. Đây cũng là **một sự đánh đổi**. Chúng ta chấp nhận loại bỏ đi một số dữ liệu hay từ nhất định từ một mẫu để giữ lại sự hữu ích từ các mẫu khác.

Nếu các bạn không muốn giữ các từ hay token ở cuối mà muốn giữ các từ ở đầu thì chúng ta cũng có thể chọn giữ phần đầu với tham số ***truncating = 'post'**.

In [12]:
padded = pad_sequences(sequences, padding='post', maxlen=6, truncating='post')
print("Kết quả các câu đã đệm:")
for seq in padded:
  print(seq)

Kết quả các câu đã đệm:
[2 3 4 5 6 0]
[2 3 4 7 6 0]
[3 8 5 2 0 0]
[ 9 10 11 12 13 14]


Như thế các từ phía đầu chuỗi đã có thể được giữ lại.

## Tổng kết phần mã hóa ngôn ngữ thành số.
- Mã hóa ngôn ngữ thành số tức là chuyển các kí tự, từ vựng hay câu thành chuỗi các số với mỗi số đại diện cho kí tự hoặc từ trong câu.
- Các phương pháp mã hóa:
  - Mã hóa theo kí tự.
  - Mã hóa theo từ.
- Bộ đệm cho các câu.
- Các tham số cho bộ đệm:
  - padding: chọn đệm phần đầu hay sau.
  - maxlen: độ dài tối đa cho các chuỗi sau khi đệm.
  - truncating: tùy chọn giữ phần đầu hay cuối của chuỗi vượt quá maxlen.

# Removing Stopwords and Cleaning text (Loại bỏ từ dừng và làm sạch văn bản)

Bắt đầu từ phần này, tụi mình sẽ tiếp cận nhiều hơn với các bộ dữ liệu thực tế nha. Điều này đồng nghĩa với việc dữ liệu sẽ chứa nhiều nhiễu hơn cũng như cần phải trải qua các bước tiền xử lý và làm sạch mà điển hình là **loại bỏ từ dừng** cũng như các **dấu câu, kí tự đặc biệt**.

> **Vậy từ dừng là những từ như thế nào?**
Hiểu đơn giản là những từ thường xuyên xuất hiện, tuy nhiên lại không đóng góp nhiều ý nghĩa cho nội dung văn bản qua đó có thể ảnh hưởng đến hiệu quả của mô hình.

Dưới đây là một danh sách nhỏ về các từ dừng nha

*(Lưu ý: danh sách có thể chưa đủ hết tất cả các từ dừng)*

![Stopwords](https://www.researchgate.net/profile/A_Zaidan/publication/228670007/figure/download/tbl2/AS:671525258657813@1537115506709/Sample-of-stop-words.png)

Tiếp đến ta đến với phần làm sạch dữ liệu văn bản thu thập được. Dữ liệu thu thập được trong quá trình cào từ các web không phải lúc nào cũng hoàn hảo cả, đôi khi sẽ chứa các **thẻ HTML** trong đó hay các từ thô lỗ, dấu câu hoặc tên riêng. Do đó ta sẽ tiến hành xử lý các phần này.

Đầu tiên là loại bỏ các thẻ HTML (HTML tags), mọi người có thể sử dụng thư viện **BeautifulSoup** để thực hiện dễ dàng hơn.

Dưới đây là ví dụ về cách dùng.

In [1]:
# Import thư viện vào
from bs4 import BeautifulSoup

In [9]:
# Tạo câu mẫu có chứa thẻ HTML trong đó
sentence = "Captain Teemo <br> on duty!" # <br> là thẻ trong HTML để xuống hàng
# Cho câu mẫu qua BeautifulSoup để tạo đối tượng soup đã được xử lý
soup = BeautifulSoup(sentence)
# Tiến hành chỉ trích xuất mỗi dữ liệu văn bản, không bao gồm các thẻ HTML
sentence = soup.get_text()
print("Câu đã được loại bỏ thẻ HTML: ", sentence)

Câu đã được loại bỏ thẻ HTML:  Captain Teemo  on duty!


Mọi người thấy đấy, thẻ <br> đã bị loại bỏ, hiện tại khoảng trắng giữa 2 từ **Teemo** và **on** là 2 kí tự khoảng cách (space)

Bây giờ tụi mình sẽ tiến hành loại bỏ từ dừng cũng như các dấu câu nha.

Ở đây, cách đơn giản nhất là mọi người lặp qua các từ và kiểm tra xem từ đó có trong danh sách từ dừng không nha, nếu có thì tiến hành loại bỏ, còn không phải thì giữ lại.

Về phần các dấu câu, chúng ta có thể sử dụng phương thức translate để tiến hành loại bỏ. Mọi người có thể sử dụng **string.punctuation** để lấy danh sách các kí tự đặc biệt và dấu câu nha.

In [4]:
import string
# In ra danh sách các dấu câu và kí tự đặc biệt.
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [5]:
# Tạo bảng mapping để loại bỏ kí tự đặc biệt
table = str.maketrans('', '', string.punctuation) # Chuyển các kí tự đặc biệt thành kí tự rỗng

In [6]:
# Lấy danh sách từ dừng, ở đây mình sử dụng thư viện nltk để lấy từ dừng trong tiếng Anh nha
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = set(stopwords.words('english'))
print("Danh sách từ dừng: ", stopwords)

Danh sách từ dừng:  {'through', 'aren', 'as', 's', 'wasn', 'we', 'yourselves', 'him', 'had', 'should', 'into', 'herself', 'needn', "that'll", 'have', "wouldn't", 'of', 'themselves', 'over', 'your', 'further', 'against', 'than', "mightn't", "hadn't", 'our', 'were', 'doesn', 'above', "wasn't", 'how', 'where', 'i', 'about', 'that', 'they', 'because', 'weren', "it's", 'a', 'to', "doesn't", 'from', 'under', 'when', 'am', 'here', 'hadn', 'what', "you'll", 'd', 'did', 'me', 'can', 'so', "don't", "didn't", "isn't", 'or', 'theirs', 'more', 'some', 'do', 'until', 'then', 'being', 'are', 'has', 'no', 'itself', 'll', "needn't", 'this', 'nor', 'after', 'the', 'just', 'myself', "should've", "you'd", 'mustn', 'been', 'their', 'is', 'don', 'same', 'all', "she's", 'while', 'does', 'doing', 'and', 'whom', 'mightn', 'at', "mustn't", 'm', 'be', 'her', 'having', 'down', 't', 'couldn', 'with', "hasn't", 'them', 'there', 'ma', "you're", 've', 'haven', "shouldn't", 'his', 'few', 'such', 'you', 'between', "sha

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [7]:
# Chuyển danh sách từ dừng sang dạng list
stopwords = list(stopwords)

In [10]:
# Chia thành danh sách các từ ra
words = sentence.split()
print("Danh sách các từ: ", words)
# Chuỗi kết quả
filtered_sentence = ""
for word in words:
  word = word.translate(table)    # Loại bỏ các kí tự đặc biệt
  if word not in stopwords:       # Kiểm tra có thuộc từ dừng không để bỏ qua.
    filtered_sentence = filtered_sentence + word + " "
print("Câu đã được tiền xử lý: ", filtered_sentence)

Danh sách các từ:  ['Captain', 'Teemo', 'on', 'duty!']
Câu đã được tiền xử lý:  Captain Teemo duty 


Đó, vậy là xong rồi á. Từ **"on"** được xác định là từ dừng và đã bị loại bỏ đi. Đồng thời dấu **"!"** cũng đã được lọc và loại bỏ.

Câu gốc:


```python
"Captain Teemo <br> on duty!"
```



Câu đã tiến hành xử lý (loại bỏ từ dùng và làm sạch):


```python
"Captain Teemo duty"
```



Tuy nhiên vẫn có những trường hợp đặc biệt dẫn đến việc làm sạch chưa thực sự hiệu quả.

Ví dụ:

Từ **you'll** khi tiến hành loại bỏ kí tự đặc biệt, nó sẽ trở thành từ **youll** dẫn đến việc kiểm tra từ dừng sẽ không phát hiện ra. Do đó chúng ta cần phải cập nhật danh sách từ dừng để chứa cả trường hợp đặc biệt **youll** này.

## Tổng kết phần loại bỏ từ dừng và làm sạch văn bảng
- Loại bỏ các đối tượng **thẻ HTML** bằng đối tượng **BeautifulSoup**.
- Loại bỏ các kí tự đặc biệt bằng **translate + string.punctuation**.
- Tải danh sách từ dừng bằng thư viện **nltk**.


# Working with Real Data Sources (Làm việc với các nguồn dữ liệu thực tế)



Tụi mình sẽ sử dụng **TFDS** đã học ở **chương 4** để tải dữ liệu nha.

Bộ dữ liệu lần này tụi mình dùng là **imdb_veviews** với 50.000 bình luận đánh giá phim được đánh nhãn là tích cực hay tiêu cực nha.


In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

Tụi mình sẽ tiến hành lặp qua bộ dữ liệu và thêm phần văn bản bình luận vào một danh sách để dễ sử lý nha. Tụi mình sử dụng **tfds.as_numpy** để đảm bảo rằng dữ liệu trả về sẽ là dạng **string** chứ không phải **tensor**.

In [6]:
train_data = tfds.as_numpy(tfds.load('imdb_reviews', split='train'))

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.AF627Z_1.0.0/imdb_reviews-train.tfrecor…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.AF627Z_1.0.0/imdb_reviews-test.tfrecord…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/incomplete.AF627Z_1.0.0/imdb_reviews-unsupervised.…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [12]:
# Kiểm tra dữ liệu của mẫu (item) đầu tiên bên trong bộ dữ liệu
item_1st = next(iter(train_data))
print(item_1st)
print(type(item_1st))

{'label': 0, 'text': b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."}
<class 'dict'>


Vậy là mỗi mẫu (item) được lưu với dạng một **dictionary** với 2 khóa là **'text' và 'label'**

In [13]:
imdb_sentences = []
# Tiến hành lặp qua từng mẫu (item) để trích xuất văn bản ra lưu vào danh sách imdb_sentences
for item in train_data:
  imdb_sentences.append(str(item['text']))

In [17]:
# Xem thử 5 bình luận đánh giá phim đầu tiên
for idx, comment in enumerate(imdb_sentences[:5]):
  print(f"Bình luận {idx+1}: {comment}")

Bình luận 1: b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."
Bình luận 2: b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep because the film was rubbish